theme = "harbor"
baseURL = "https://duncip.netlify.app/"
title = "Duncan Pastoors"
paginate = 4
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
custom_css = ["dp-styles.css"]
pygmentsUseClasses = true

[Author]
  name = "duncan pastoors"

[outputs]
    section = ["JSON", "HTML"]


[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3


[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "dp_logo.png"
    width = 50
    height = 50
    alt = "Logo"

[permalinks]
  post = "/:year/:month/:day/:slug/"
  
  